### ISSUE TITLE
1.3 Adding an example user

### ISSUE THREAD

**Issue by marktani** [graphcool/docs#20]
> Note: moved from [here](https://github.com/graphcool/dashboard/issues/214)

Not sure what is going on here. You probably arent done yet. Here is the feedback anyway. On https://docs.graph.cool/guides/implementing-business-logic-using-actions you instruct the user to create a new node and add there email. Images below is what it looks like. You cant really tell what you are supposed to do other than click the green ADD NODE button. After that, the steps are kinda not descriptive. If you click through it you get to notice there is another line on the table. The cells are not labeled and there is no cell for the users name. 
## Step 1
![graphcool4-addnode](https://cloud.githubusercontent.com/assets/2370391/18785818/d0aafc10-819a-11e6-9803-8884a65fe2d8.PNG)
## Step 2
![graphcool4-addnode2 5](https://cloud.githubusercontent.com/assets/2370391/18785819/d0b04fda-819a-11e6-9e0b-15c29f6225ed.PNG)
## Step 3
![graphcool4-addnode2](https://cloud.githubusercontent.com/assets/2370391/18785821/d0b36f58-819a-11e6-9aa3-d704012252ed.PNG)
## Step 4
![graphcool4-addnode3](https://cloud.githubusercontent.com/assets/2370391/18785822/d0b684a4-819a-11e6-950b-ab375f546986.PNG)
## Step 5
![graphcool4-addnode4](https://cloud.githubusercontent.com/assets/2370391/18785817/d0a73288-819a-11e6-85e8-1b8b9fbb3aa4.PNG)

**Comment by marktani** [comment]
What you are supposed to do is adding a new String field called `name` to the `User` model. The `email` field is currently automatically added, but we might change that in the future.

In any case, the first thing you should do for the guide (in section 1.1) is making sure that the `User` model has the `name` and `email` fields which are of type String. Then, in section 1.2, you create relations between `User` and `Post  and `Comment` respectively.

Did you finish the getting started tour or the first guide? I want to make sure the instructions are clear and understandable for readers that finished either of them.

**Comment by aarmand** [comment]
Looks like what happened here is that when I went through the process the first time, things were not saved. I dont know why this happened but I had to go back through the process. The edits are now there and this worked as intended.

**Comment by marktani** [comment]
Ok great. Sorry for the trouble.

**Comment by aarmand** [comment]
No trouble. Having fun. Thanks.
