### ISSUE TITLE
1.2 Associating posts and comments with an author

### ISSUE THREAD

**Issue by aarmand** [graphcool/docs#21]
In docs [here](https://docs.graph.cool/guides/implementing-business-logic-using-actions), we are instructed to create a relation and choose 'author' and 'posts' for the field names. 'author' is not an available fieldname. I dont think that the docs request the user to create an author field or an Author model. Seems we should have an Author model for it to show in the Models dropdown field. Did you mean 'User' rather than 'author' when you say "Let's call the relation between User and Post PostAuthor and choose **author** and posts for the field names."?
![graphcool6-userfieldnames](https://cloud.githubusercontent.com/assets/2370391/18807920/62afdd06-8254-11e6-9c42-2ffa0bf40308.PNG)

**Comment by marktani** [comment]
This might not be obvious from the Relation UI, but you can rename fields when creating a new Relation. These fields will be created as part of the Relation. For this paragraph you are indeed supposed to choose `User` for model and rename the field `user` to `author`.

**Comment by aarmand** [comment]
Cool. I actually looked for that so as not to waste your time but didnt trigger it. So the suggestion, obviously, is make that more visible, i guess.
