### ISSUE TITLE
3. Creating a new Action

### ISSUE THREAD

**Issue by aarmand** [graphcool/docs#22]
In [3. Creating a new Action](https://docs.graph.cool/guides/implementing-business-logic-using-actions),

The guide says to create the following query. At this point, though, there is no "text" node, I think you want 'comment' on 'Comment' model.  
```
{
  createdNode {
    **text**
    author {
      name
    }
    post {
      author {
        name
        email
      }
    }
  }
```

**Comment by marktani** [comment]
In the first guide you are supposed to create the `text` field on the `Comment` model: [2. Defining Relations between your models](https://docs.graph.cool/guides/setting-up-a-graphql-backend-in-5-minutes).

**Comment by aarmand** [comment]
Thanks for that. My fault i missed that. Did I also miss creating 'author' field on the User? In "Creating New Actions" you ask the user to create relations:
```
Let's call the relation between User and Post PostAuthor and choose 
author and posts for the field names. Make sure to select one for User and many for Post.
```
I could not find where we created author.  Might same issue as here: https://github.com/graphcool/docs/issues/21#issuecomment-249380392
