### ISSUE TITLE
Creating Relations - Suggestion

### ISSUE THREAD

**Issue by aarmand** [graphcool/docs#23]
My experience in graphql, limited as it is, is that we create our types and schema's first then create queries, interfaces, whatever based on what we have defined in the schema. In the graph.cool, Relations create method, the field name we enter is really a field name we are creating on the target model. I think this is someone counter intuitive given the graphql documentation and how its presented. You guys create new fields as you need them, if they are not already created. This is not evident in the docs at all and seriously think its worth noting as it changes the thinking about creating these things.

**Comment by marktani** [comment]
We try to tackle this topics with the onboarding experience that we highly reworked in the last few days.

Feel free to hit me up in Slack if you want to share some other thoughts on this topic :)
