### ISSUE TITLE
Auth example

### ISSUE THREAD

**Issue by thomaswright** [graphcool/docs#43]
I modified the auth0-lock example to use the apollo client, react-router v4, pull some auth profile data, and check for token expiration. 

https://github.com/thomaswright/graphcool-auth0-apollo-auth-example

**Comment by marktani** [comment]
looks great! do you mind joining [our Slack channel](http://slack.graph.cool) to discuss a few things with me?

**Comment by thomaswright** [comment]
Okay, cool. My slack handle is tom.

**Comment by marktani** [comment]
I sent you a message, would love to hear back from you :slightly_smiling_face:
